version: '3'

services:
  # Django web application
  web:
    image: python:3.9
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://user:password@db:3307/dbname

  # MySQL database
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  # Additional services (e.g., Celery, Redis, etc.) can be added as needed
