version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3309:3306"