# Generated by Django 4.2.6 on 2023-12-05 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="template",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
