# Generated by Django 4.2.6 on 2024-01-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_bounced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="is_replied",
            field=models.BooleanField(default=False),
        ),
    ]
