# Generated by Django 4.2.6 on 2024-01-03 05:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailvariant",
            name="content",
            field=ckeditor.fields.RichTextField(
                help_text="{{name}} | {{first_name}} | {{last_name}} | {{primary_phone}} | {{primary_email}} | {{primary_phone}} | {{lead_display_name}} | {{lead_custom_company_address}}"
            ),
        ),
        migrations.AlterField(
            model_name="emailvariant",
            name="subject",
            field=ckeditor.fields.RichTextField(
                help_text="{{name}} | {{first_name}} | {{last_name}} | {{primary_phone}} | {{primary_email}} | {{primary_phone}} | {{lead_display_name}} | {{lead_custom_company_address}}"
            ),
        ),
        migrations.AlterField(
            model_name="followupemail",
            name="content",
            field=ckeditor.fields.RichTextField(
                help_text="{{name}} | {{first_name}} | {{last_name}} | {{primary_phone}} | {{primary_email}} | {{primary_phone}} | {{lead_display_name}} | {{lead_custom_company_address}}"
            ),
        ),
        migrations.AlterField(
            model_name="followupemail",
            name="subject",
            field=ckeditor.fields.RichTextField(
                default=1,
                help_text="{{name}} | {{first_name}} | {{last_name}} | {{primary_phone}} | {{primary_email}} | {{primary_phone}} | {{lead_display_name}} | {{lead_custom_company_address}}",
            ),
            preserve_default=False,
        ),
    ]
