# Generated by Django 4.2.6 on 2024-01-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0002_alter_emailvariant_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupemail",
            name="tag",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="followupemail",
            name="title",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
