# Generated by Django 4.2.6 on 2023-12-13 04:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0002_alter_emailvariant_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailvariant",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
