# Generated by Django 4.2.6 on 2024-01-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0002_contact_is_bounced_contact_is_replied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailvariant",
            name="subject",
            field=models.TextField(
                help_text="{{name}} | {{first_name}} | {{last_name}} | {{primary_phone}} | {{primary_email}} | {{primary_phone}} | {{lead_display_name}} | {{lead_custom_company_address}}"
            ),
        ),
        migrations.AlterField(
            model_name="followupemail",
            name="subject",
            field=models.TextField(
                blank=True,
                help_text="{{name}} | {{first_name}} | {{last_name}} | {{primary_phone}} | {{primary_email}} | {{primary_phone}} | {{lead_display_name}} | {{lead_custom_company_address}}",
                null=True,
            ),
        ),
    ]
