# Generated by Django 4.2.6 on 2023-12-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0003_alter_emailvariant_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="lead_custom_company_description",
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
