# Generated by Django 4.2.6 on 2023-12-05 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0003_alter_template_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=250)),
                ("email", models.CharField(max_length=500)),
                ("reply_to", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "ConnectedAccount",
                "verbose_name_plural": "ConnectedAccounts",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("first_name", models.CharField(blank=True, max_length=250, null=True)),
                ("last_name", models.CharField(blank=True, max_length=250, null=True)),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "primary_phone",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "other_phones",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "primary_email",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "other_emails",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "linkedin_profile",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "custom_first_phone",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "date_created",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("lead_id", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "lead_display_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("lead_url", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "lead_status_label",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_company_address",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_company_city",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_company_country",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_company_description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_company_industry",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_company_li_profile",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_company_linkedin",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_company_phone",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_company_phone1",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_company_state",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_contact_job_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_contact_li_profile_url",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_contact_linkedin_profile",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_contact_location",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_contact_phone_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_contact_state",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_corporate_phone",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_person_assigned",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_custom_person_linkedin_url",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lead_html_url",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
    ]
