# Generated by Django 4.2.6 on 2024-01-14 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0003_alter_emailvariant_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="followupemail",
            name="email",
        ),
    ]
