# Generated by Django 4.2.6 on 2023-12-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0004_connectedaccount_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="lead_custom_contact_city",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
