# Generated by Django 4.2.6 on 2024-01-03 07:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0004_alter_emailvariant_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailvariant",
            name="tag",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("tag1", "tag1"),
                    ("tag2", "tag2"),
                    ("tag3", "tag3"),
                    ("tag4", "tag4"),
                    ("tag5", "tag5"),
                ],
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="followupemail",
            name="tag",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("tag1", "tag1"),
                    ("tag2", "tag2"),
                    ("tag3", "tag3"),
                    ("tag4", "tag4"),
                    ("tag5", "tag5"),
                ],
                max_length=1000,
            ),
        ),
    ]
