# Generated by Django 4.2.6 on 2024-01-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0004_remove_followupemail_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="primary_reply_to",
            field=models.CharField(
                blank=True,
                help_text="primary reply to email (optional)",
                max_length=250,
                null=True,
            ),
        ),
    ]
