# Generated by Django 4.2.6 on 2023-12-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0004_alter_contact_lead_custom_company_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="waiting_time",
            field=models.IntegerField(default=1, help_text="waiting time in hour"),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="max_limit_per_day",
            field=models.IntegerField(
                default=50, help_text="maximum email send limit from an account"
            ),
        ),
    ]
