# Generated by Django 4.2.6 on 2023-12-05 08:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0005_contact_lead_custom_contact_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPointer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pointer", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Contact Pointer",
                "verbose_name_plural": "Contacts Pointer",
            },
        ),
        migrations.CreateModel(
            name="SentEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "connected_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="orm.connectedaccount",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="orm.contact"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="orm.template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sent Email",
                "verbose_name_plural": "Sent Emails",
            },
        ),
        migrations.CreateModel(
            name="EmailStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_sent", models.BooleanField(default=False)),
                ("email_delivered", models.BooleanField(default=False)),
                ("email_complained", models.BooleanField(default=False)),
                ("email_bounced", models.BooleanField(default=False)),
                ("email_opened", models.BooleanField(default=False)),
                ("email_clicked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="orm.sentemail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Status",
                "verbose_name_plural": "Emails Status",
            },
        ),
    ]
