# Generated by Django 4.2.6 on 2023-12-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0005_configuration_waiting_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupemail",
            name="sent_after",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="this followup email will sent after specified day from the original email",
            ),
        ),
        migrations.AddField(
            model_name="sentemail",
            name="is_followup",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="waiting_time",
            field=models.IntegerField(default=1, help_text="waiting time in minutes"),
        ),
    ]
