# Generated by Django 4.2.6 on 2024-01-03 08:14

import ckeditor.fields
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0005_alter_emailvariant_tag_alter_followupemail_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailvariant",
            name="tag",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("tag1", "tag1"),
                    ("tag2", "tag2"),
                    ("tag3", "tag3"),
                    ("tag4", "tag4"),
                    ("tag5", "tag5"),
                ],
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="followupemail",
            name="subject",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="{{name}} | {{first_name}} | {{last_name}} | {{primary_phone}} | {{primary_email}} | {{primary_phone}} | {{lead_display_name}} | {{lead_custom_company_address}}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="followupemail",
            name="tag",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("tag1", "tag1"),
                    ("tag2", "tag2"),
                    ("tag3", "tag3"),
                    ("tag4", "tag4"),
                    ("tag5", "tag5"),
                ],
                max_length=1000,
                null=True,
            ),
        ),
    ]
