# Generated by Django 4.2.6 on 2024-01-03 08:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0006_alter_emailvariant_tag_alter_followupemail_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupemail",
            name="tag",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("tag1", "tag1"),
                    ("tag2", "tag2"),
                    ("tag3", "tag3"),
                    ("tag4", "tag4"),
                    ("tag5", "tag5"),
                ],
                max_length=1000,
                null=True,
            ),
        ),
    ]
