# Generated by Django 4.2.6 on 2023-12-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0006_contactpointer_sentemail_emailstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectedaccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="template",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
