# Generated by Django 4.2.6 on 2024-01-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0007_alter_followupemail_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentemail",
            name="is_automated_reply",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sentemail",
            name="is_lead_replied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sentemail",
            name="is_positive_reply",
            field=models.BooleanField(default=False),
        ),
    ]
