# Generated by Django 4.2.6 on 2023-12-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0008_configuration_delete_contactpointer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="config",
            field=models.CharField(default="Config", max_length=100),
        ),
    ]
