# Generated by Django 4.2.6 on 2023-12-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0008_remove_followupemail_sent_after_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupemail",
            name="wait_for",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="this followup email will wait specified day from the original email",
            ),
        ),
    ]
