# Generated by Django 4.2.6 on 2023-12-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0009_configuration_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuration",
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configuration",
            },
        ),
        migrations.AlterField(
            model_name="configuration",
            name="config",
            field=models.CharField(default="Config", editable=False, max_length=100),
        ),
    ]
