# Generated by Django 4.2.6 on 2023-12-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0009_alter_followupemail_wait_for"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sentemail",
            old_name="template",
            new_name="email_variant",
        ),
    ]
