# Generated by Django 4.2.6 on 2023-12-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0010_alter_configuration_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentemail",
            name="resend_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="tag",
            field=models.CharField(default="tag1", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
