# Generated by Django 4.2.6 on 2023-12-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0010_rename_template_sentemail_email_variant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sentemail",
            old_name="email_variant",
            new_name="template",
        ),
    ]
