# Generated by Django 4.2.6 on 2023-12-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0011_sentemail_resend_id_template_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="primary_reply_to",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
