# Generated by Django 4.2.6 on 2023-12-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0012_configuration_primary_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="waiting_time",
            field=models.IntegerField(default=60, help_text="waiting time in seconds"),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="max_limit_per_day",
            field=models.IntegerField(
                default=50, help_text="maximum email send limit by an account"
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="primary_reply_to",
            field=models.CharField(
                blank=True,
                help_text="primary reply to email",
                max_length=250,
                null=True,
            ),
        ),
    ]
