# Generated by Django 4.2.6 on 2023-12-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0013_alter_sentemail_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_unsubscribe",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="unsubscribe_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
