# Generated by Django 4.2.6 on 2023-12-14 10:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0015_alter_emailvariant_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupemail",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
